version: '3'

networks:
  laravel-blog:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - redis
      - webserver
    networks:
      - laravel-blog

  mysql:
    image: mysql:8
    restart: unless-stopped
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "8082:3306"
    environment:
      MYSQL_DATABASE: laravel-blog
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - database:/var/lib/mysql
    networks:
      - laravel-blog

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel-blog

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel-blog

volumes:
  database:
